### ISSUE TITLE
Custom badge

### ISSUE THREAD

**Issue by alexnix** [vitorhugods/AvatarView#25]
Is there a way to load an actual image for the badge?

**Comment by vitorhugods** [comment]
Only solid colours are currently supported.

I guess it would be possible to accept drawables and modifying the `onDraw` function to draw it instead of solid colours.

At the moment I have no plans in adding new features to this library, but I am thinking about re-implementing it using Compose and making it more customisable.

Haven't taken any actions towards this yet.
