### ISSUE TITLE
Compativilidad con jitpack.io

### ISSUE THREAD

**Issue by cz9dev** [vitorhugods/AvatarView#29]
desde jitpack.io no puedo incluir la lib en mis proyectos, solo puedo incluir versiones hasta la 1.0.0

**Library Version:**
 - Version [1.2.0]

**Comment by vitorhugods** [comment]
The library was never available on Jitpack.io. And [1.2.0 is only available on Maven Central](https://mvnrepository.com/artifact/xyz.schwaab/avvylib).

So you need to define the repository in the Gradle configuration:
```kotlin
repositories {
    mavenCentral()
}
```

It was available on Jcenter until the version 1.1.1, but [JCenter is dead since 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

-----

La lib nunca estuve disponibile en Jitpack.io. E la versión 1.2.0 [está solamente en Maven Central](https://mvnrepository.com/artifact/xyz.schwaab/avvylib).

Entonces necesita definir lo repositorio en su configuración Gradle:
```kotlin
repositories {
    mavenCentral()
}
```

Era disponibile en JCenter hasta la version 1.1.1, pero [JCenter esta muerto desde 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).
